baseurl = "https://johnmath.github.io/"
languageCode = "en-us"
title = "John Abascal"
pagination.pagerSize = 5

[markup.goldmark.renderer]
  unsafe = true

[markup.highlight]
  noClasses = false

[params]
  contentTypeName = "posts"
  showMenuItems = 3
  fullWidthTheme = false
  centerTheme = false
  showLanguageSelector = false
  favicon = "favicon.png"
  author = "John Abascal"
  description = "John Abascal - Computer Science PhD Student at Northeastern University specializing in machine learning, privacy, and security."
  
[params.social]
  linkedin = "johnabascal"
  github = "johnmath"
  googlescholar = "3jYQ3FsAAAAJ"
  orcid = "0009-0005-5820-5476"
  email = "abascal.j@northeastern.edu" 


[languages]
  [languages.en]
    title = "John Abascal"
    
    [languages.en.params]
      subtitle = "Computer Science PhD Student at Northeastern University"
      keywords = "John Abascal, computer science, machine learning, privacy, differential privacy, PhD, Northeastern University, researcher, AI, security"
      copyright = "Â© 2025 John Abascal"
      menuMore = "Show more"
      readMore = "Read more"
      readOtherPosts = "Read other posts"
      newerPosts = "Newer posts"
      olderPosts = "Older posts"
      missingContentMessage = "Page not found..."
      missingBackButtonLabel = "Back to home page"
      minuteReadingTime = "min read"
      words = "words"

      [languages.en.params.logo]
        logoText = "$ john"
        logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/"
      [[languages.en.menu.main]]
        identifier = "cv"
        name = "CV"
        url = "/cv"
      [[languages.en.menu.main]]
        identifier = "research"
        name = "Research"
        url = "/research"

[module]
  [module.hugoVersion]
    extended = true
    min = '0.90.0'
  [[module.imports]]
    path = 'github.com/panr/hugo-theme-terminal/v4'
